// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        v5.29.2
// source: log_server.proto

package log_server_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PostLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	RequestPath   string                 `protobuf:"bytes,2,opt,name=request_path,json=requestPath,proto3" json:"request_path,omitempty"`
	StatusCode    string                 `protobuf:"bytes,3,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Msg           string                 `protobuf:"bytes,4,opt,name=msg,proto3" json:"msg,omitempty"`
	Level         string                 `protobuf:"bytes,5,opt,name=level,proto3" json:"level,omitempty"`
	Time          string                 `protobuf:"bytes,6,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostLogRequest) Reset() {
	*x = PostLogRequest{}
	mi := &file_log_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostLogRequest) ProtoMessage() {}

func (x *PostLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_log_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostLogRequest.ProtoReflect.Descriptor instead.
func (*PostLogRequest) Descriptor() ([]byte, []int) {
	return file_log_server_proto_rawDescGZIP(), []int{0}
}

func (x *PostLogRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *PostLogRequest) GetRequestPath() string {
	if x != nil {
		return x.RequestPath
	}
	return ""
}

func (x *PostLogRequest) GetStatusCode() string {
	if x != nil {
		return x.StatusCode
	}
	return ""
}

func (x *PostLogRequest) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *PostLogRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *PostLogRequest) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

// 不返回答复，日志可丢失
type PostLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostLogResponse) Reset() {
	*x = PostLogResponse{}
	mi := &file_log_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostLogResponse) ProtoMessage() {}

func (x *PostLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_log_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostLogResponse.ProtoReflect.Descriptor instead.
func (*PostLogResponse) Descriptor() ([]byte, []int) {
	return file_log_server_proto_rawDescGZIP(), []int{1}
}

var File_log_server_proto protoreflect.FileDescriptor

var file_log_server_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6c, 0x6f, 0x67, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa8, 0x01, 0x0a, 0x0e, 0x50, 0x6f,
	0x73, 0x74, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f,
	0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x50, 0x61, 0x74, 0x68, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65,
	0x76, 0x65, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x69, 0x6d, 0x65, 0x22, 0x11, 0x0a, 0x0f, 0x50, 0x6f, 0x73, 0x74, 0x4c, 0x6f, 0x67, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x48, 0x0a, 0x0a, 0x4c, 0x6f, 0x67, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3a, 0x0a, 0x07, 0x50, 0x6f, 0x73, 0x74, 0x4c, 0x6f, 0x67,
	0x12, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x4c, 0x6f, 0x67,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x50, 0x6f, 0x73, 0x74, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x1f, 0x5a, 0x1d, 0x2e, 0x2f, 0x6c, 0x6f, 0x67, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x3b, 0x6c, 0x6f, 0x67, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_log_server_proto_rawDescOnce sync.Once
	file_log_server_proto_rawDescData = file_log_server_proto_rawDesc
)

func file_log_server_proto_rawDescGZIP() []byte {
	file_log_server_proto_rawDescOnce.Do(func() {
		file_log_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_log_server_proto_rawDescData)
	})
	return file_log_server_proto_rawDescData
}

var file_log_server_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_log_server_proto_goTypes = []any{
	(*PostLogRequest)(nil),  // 0: proto.PostLogRequest
	(*PostLogResponse)(nil), // 1: proto.PostLogResponse
}
var file_log_server_proto_depIdxs = []int32{
	0, // 0: proto.LogService.PostLog:input_type -> proto.PostLogRequest
	1, // 1: proto.LogService.PostLog:output_type -> proto.PostLogResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_log_server_proto_init() }
func file_log_server_proto_init() {
	if File_log_server_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_log_server_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_log_server_proto_goTypes,
		DependencyIndexes: file_log_server_proto_depIdxs,
		MessageInfos:      file_log_server_proto_msgTypes,
	}.Build()
	File_log_server_proto = out.File
	file_log_server_proto_rawDesc = nil
	file_log_server_proto_goTypes = nil
	file_log_server_proto_depIdxs = nil
}
