// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        v5.29.2
// source: risk_server.proto

package risk_server_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RiskLoginIpAndAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Agent         string                 `protobuf:"bytes,3,opt,name=agent,proto3" json:"agent,omitempty"`
	LoginStatus   string                 `protobuf:"bytes,4,opt,name=login_status,json=loginStatus,proto3" json:"login_status,omitempty"` // FAIL 登录失败, SUCCESS 登录成功
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiskLoginIpAndAgentRequest) Reset() {
	*x = RiskLoginIpAndAgentRequest{}
	mi := &file_risk_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskLoginIpAndAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskLoginIpAndAgentRequest) ProtoMessage() {}

func (x *RiskLoginIpAndAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_risk_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskLoginIpAndAgentRequest.ProtoReflect.Descriptor instead.
func (*RiskLoginIpAndAgentRequest) Descriptor() ([]byte, []int) {
	return file_risk_server_proto_rawDescGZIP(), []int{0}
}

func (x *RiskLoginIpAndAgentRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RiskLoginIpAndAgentRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *RiskLoginIpAndAgentRequest) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *RiskLoginIpAndAgentRequest) GetLoginStatus() string {
	if x != nil {
		return x.LoginStatus
	}
	return ""
}

type RiskLoginIpAndAgentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 老三样，返给前端的,被拦截需要返回，通过就不用
	Code          int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	StatusCode    string `protobuf:"bytes,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Msg           string `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	RiskStatus    string `protobuf:"bytes,4,opt,name=risk_status,json=riskStatus,proto3" json:"risk_status,omitempty"` // 拦截状态 PASS 放行， WARN 警告， RISK 拦截
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiskLoginIpAndAgentResponse) Reset() {
	*x = RiskLoginIpAndAgentResponse{}
	mi := &file_risk_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskLoginIpAndAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskLoginIpAndAgentResponse) ProtoMessage() {}

func (x *RiskLoginIpAndAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_risk_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskLoginIpAndAgentResponse.ProtoReflect.Descriptor instead.
func (*RiskLoginIpAndAgentResponse) Descriptor() ([]byte, []int) {
	return file_risk_server_proto_rawDescGZIP(), []int{1}
}

func (x *RiskLoginIpAndAgentResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RiskLoginIpAndAgentResponse) GetStatusCode() string {
	if x != nil {
		return x.StatusCode
	}
	return ""
}

func (x *RiskLoginIpAndAgentResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *RiskLoginIpAndAgentResponse) GetRiskStatus() string {
	if x != nil {
		return x.RiskStatus
	}
	return ""
}

var File_risk_server_proto protoreflect.FileDescriptor

var file_risk_server_proto_rawDesc = []byte{
	0x0a, 0x11, 0x72, 0x69, 0x73, 0x6b, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7e, 0x0a, 0x1a, 0x52, 0x69,
	0x73, 0x6b, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x49, 0x70, 0x41, 0x6e, 0x64, 0x41, 0x67, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x70, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x6c, 0x6f, 0x67, 0x69, 0x6e,
	0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6c,
	0x6f, 0x67, 0x69, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x85, 0x01, 0x0a, 0x1b, 0x52,
	0x69, 0x73, 0x6b, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x49, 0x70, 0x41, 0x6e, 0x64, 0x41, 0x67, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x1f,
	0x0a, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73,
	0x67, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x69, 0x73, 0x6b, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x69, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x32, 0x6b, 0x0a, 0x0b, 0x52, 0x69, 0x73, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x5c, 0x0a, 0x13, 0x52, 0x69, 0x73, 0x6b, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x49, 0x70,
	0x41, 0x6e, 0x64, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x52, 0x69, 0x73, 0x6b, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x49, 0x70, 0x41, 0x6e, 0x64, 0x41,
	0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x69, 0x73, 0x6b, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x49, 0x70, 0x41,
	0x6e, 0x64, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x21, 0x5a, 0x1f, 0x2e, 0x2f, 0x72, 0x69, 0x73, 0x6b, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x3b, 0x72, 0x69, 0x73, 0x6b, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_risk_server_proto_rawDescOnce sync.Once
	file_risk_server_proto_rawDescData = file_risk_server_proto_rawDesc
)

func file_risk_server_proto_rawDescGZIP() []byte {
	file_risk_server_proto_rawDescOnce.Do(func() {
		file_risk_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_risk_server_proto_rawDescData)
	})
	return file_risk_server_proto_rawDescData
}

var file_risk_server_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_risk_server_proto_goTypes = []any{
	(*RiskLoginIpAndAgentRequest)(nil),  // 0: proto.RiskLoginIpAndAgentRequest
	(*RiskLoginIpAndAgentResponse)(nil), // 1: proto.RiskLoginIpAndAgentResponse
}
var file_risk_server_proto_depIdxs = []int32{
	0, // 0: proto.RiskService.RiskLoginIpAndAgent:input_type -> proto.RiskLoginIpAndAgentRequest
	1, // 1: proto.RiskService.RiskLoginIpAndAgent:output_type -> proto.RiskLoginIpAndAgentResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_risk_server_proto_init() }
func file_risk_server_proto_init() {
	if File_risk_server_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_risk_server_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_risk_server_proto_goTypes,
		DependencyIndexes: file_risk_server_proto_depIdxs,
		MessageInfos:      file_risk_server_proto_msgTypes,
	}.Build()
	File_risk_server_proto = out.File
	file_risk_server_proto_rawDesc = nil
	file_risk_server_proto_goTypes = nil
	file_risk_server_proto_depIdxs = nil
}
