// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        v5.29.2
// source: ai_server.proto

package ai_server_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TalkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TalkRequest) Reset() {
	*x = TalkRequest{}
	mi := &file_ai_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TalkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TalkRequest) ProtoMessage() {}

func (x *TalkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TalkRequest.ProtoReflect.Descriptor instead.
func (*TalkRequest) Descriptor() ([]byte, []int) {
	return file_ai_server_proto_rawDescGZIP(), []int{0}
}

func (x *TalkRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type TalkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      string                 `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TalkResponse) Reset() {
	*x = TalkResponse{}
	mi := &file_ai_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TalkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TalkResponse) ProtoMessage() {}

func (x *TalkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TalkResponse.ProtoReflect.Descriptor instead.
func (*TalkResponse) Descriptor() ([]byte, []int) {
	return file_ai_server_proto_rawDescGZIP(), []int{1}
}

func (x *TalkResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

var File_ai_server_proto protoreflect.FileDescriptor

var file_ai_server_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x61, 0x69, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x25, 0x0a, 0x0b, 0x54, 0x61, 0x6c, 0x6b,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x22,
	0x2a, 0x0a, 0x0c, 0x54, 0x61, 0x6c, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x3e, 0x0a, 0x09, 0x41,
	0x49, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x31, 0x0a, 0x04, 0x54, 0x61, 0x6c, 0x6b,
	0x12, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x61, 0x6c, 0x6b, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x61, 0x6c,
	0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x42, 0x1d, 0x5a, 0x1b, 0x2e,
	0x2f, 0x61, 0x69, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x3b, 0x61, 0x69, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_ai_server_proto_rawDescOnce sync.Once
	file_ai_server_proto_rawDescData = file_ai_server_proto_rawDesc
)

func file_ai_server_proto_rawDescGZIP() []byte {
	file_ai_server_proto_rawDescOnce.Do(func() {
		file_ai_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_ai_server_proto_rawDescData)
	})
	return file_ai_server_proto_rawDescData
}

var file_ai_server_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ai_server_proto_goTypes = []any{
	(*TalkRequest)(nil),  // 0: proto.TalkRequest
	(*TalkResponse)(nil), // 1: proto.TalkResponse
}
var file_ai_server_proto_depIdxs = []int32{
	0, // 0: proto.AIService.Talk:input_type -> proto.TalkRequest
	1, // 1: proto.AIService.Talk:output_type -> proto.TalkResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ai_server_proto_init() }
func file_ai_server_proto_init() {
	if File_ai_server_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ai_server_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_server_proto_goTypes,
		DependencyIndexes: file_ai_server_proto_depIdxs,
		MessageInfos:      file_ai_server_proto_msgTypes,
	}.Build()
	File_ai_server_proto = out.File
	file_ai_server_proto_rawDesc = nil
	file_ai_server_proto_goTypes = nil
	file_ai_server_proto_depIdxs = nil
}
